sudo: required
# super user permission required
services:
    - docker

before_install: 
    - docker build -t TestImage -f Dockerfile.dev .
    # build a docker image named "TestImage" using Dockerfile.dev, by doing this we don't need to copy 
    # paste the randomly generated docker id.

script:
    - docker run -e CI=true TestImage npm run test
    # run npm test inside the docker image named "TestImage"
    